rule esm_master_install_tux:
    output:
        touch("results/tux.installed"),
    params:
        model="tux",
        version="1.0",
    log:
        "logs/esm_master/tux.log",
    wrapper:
        "https://github.com/pgierz/snakemake-wrapper-esm-master/raw/master/esm_master_install"
